// css
import "./main.css";
// bootstrap import
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "./components/BootstrapClient/BootstrapClient";

export const metadata = {
  title: "ESSETEC",
  description: "Generated by ❤️",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
