import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./main.css";
import BootstrapClient from "./Components/BootstrapClient/BootstrapClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ESSETEC",
  description: "Generated by ❤️",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
